#if !defined(____HEADER_GUARD_CHAR_IS__C)
#define ____HEADER_GUARD_CHAR_IS__C



#include "bool_type.h"



#define ____char_is_lower_function_declaration bool_t char_is_lower(char char_)
#define ____char_is_upper_function_declaration bool_t char_is_upper(char char_)
#define ____char_is_alpha_function_declaration bool_t char_is_alpha(char char_)
#define ____char_is_digit_function_declaration bool_t char_is_digit(char char_)
#define ____char_is_alphanumeric_function_declaration bool_t char_is_alphanumeric(char char_)
#define ____char_is_whitespace_function_declaration bool_t char_is_whitespace(char char_)
#define ____char_is_escapeChar_function_declaration bool_t char_is_escapeChar(char char_)



____char_is_lower_function_declaration;
____char_is_upper_function_declaration;
____char_is_alpha_function_declaration;
____char_is_digit_function_declaration;
____char_is_alphanumeric_function_declaration;
____char_is_whitespace_function_declaration;
____char_is_escapeChar_function_declaration;



#endif