#include "detectUnsignedOverflow.h"



____FUNCTION_DECLARATION_detectUnsignedAdditionOverflow_TEMPLATE(8) ____FUNCTION_BODY_detectUnsignedAdditionOverflow_TEMPLATE(8)

____FUNCTION_DECLARATION_detectUnsignedAdditionOverflow_TEMPLATE(16) ____FUNCTION_BODY_detectUnsignedAdditionOverflow_TEMPLATE(16)

____FUNCTION_DECLARATION_detectUnsignedAdditionOverflow_TEMPLATE(32) ____FUNCTION_BODY_detectUnsignedAdditionOverflow_TEMPLATE(32)

____FUNCTION_DECLARATION_detectUnsignedAdditionOverflow_TEMPLATE(64) ____FUNCTION_BODY_detectUnsignedAdditionOverflow_TEMPLATE(64)