#include "int_isOdd.h"


____FUNCTION_DECLARATION_int_isOdd_TEMPLATE(u, 8) ____FUNCTION_BODY_int_isOdd_TEMPLATE(u, 8)
____FUNCTION_DECLARATION_int_isOdd_TEMPLATE(u, 16) ____FUNCTION_BODY_int_isOdd_TEMPLATE(u, 16)
____FUNCTION_DECLARATION_int_isOdd_TEMPLATE(u, 32) ____FUNCTION_BODY_int_isOdd_TEMPLATE(u, 32)
____FUNCTION_DECLARATION_int_isOdd_TEMPLATE(u, 64) ____FUNCTION_BODY_int_isOdd_TEMPLATE(u, 64)

____FUNCTION_DECLARATION_int_isOdd_TEMPLATE(s, 8) ____FUNCTION_BODY_int_isOdd_TEMPLATE(s, 8)
____FUNCTION_DECLARATION_int_isOdd_TEMPLATE(s, 16) ____FUNCTION_BODY_int_isOdd_TEMPLATE(s, 16)
____FUNCTION_DECLARATION_int_isOdd_TEMPLATE(s, 32) ____FUNCTION_BODY_int_isOdd_TEMPLATE(s, 32)
____FUNCTION_DECLARATION_int_isOdd_TEMPLATE(s, 64) ____FUNCTION_BODY_int_isOdd_TEMPLATE(s, 64)